// <auto-generated />
using System;
using IManage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IManage.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20190322134155_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IManage.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FIO")
                        .IsRequired();

                    b.Property<int>("Value");

                    b.Property<string>("passport");

                    b.HasKey("ClientId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("IManage.Models.Investment", b =>
                {
                    b.Property<int>("InvestmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Balance");

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("DateOpen");

                    b.Property<int>("ProgId");

                    b.HasKey("InvestmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProgId");

                    b.ToTable("Investment");
                });

            modelBuilder.Entity("IManage.Models.Prog", b =>
                {
                    b.Property<int>("ProgId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("months");

                    b.Property<int>("percent");

                    b.HasKey("ProgId");

                    b.ToTable("Prog");
                });

            modelBuilder.Entity("IManage.Models.Investment", b =>
                {
                    b.HasOne("IManage.Models.Client", "Client")
                        .WithMany("Investments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IManage.Models.Prog", "Prog")
                        .WithMany("Investments")
                        .HasForeignKey("ProgId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
